 **bold text**

Generate a softmax multiclass model for a X dataset. This dataset contains 5 data of 6 feaatures each data.

X should be classified in three categories with a sofmax multiclass model.



1.   Generate a random version of the dataset X.
2.   Generate a random version of the dataset W and B.
3.   Find Z, Y_prob and Y_class




In [ ]:
import numpy as np

In [ ]:
ndata = 5
nfeatures = 6
ncategories = 3
# Creating the sintetic data
np.random.seed(seed=35)
nx=nfeatures
m = ndata
c=ncategories
W=np.random.normal(size=(c,nx))
X=np.random.normal(size=(nx,m))
B=np.random.normal(size=(c,1))

# Calculating the scores z
#
#

z = np.matmul(W,X) + B

# Calculating the probabilities Y_prob
#
#

Y_prob = np.exp(z) / np.sum(np.exp(z), axis = 0)
# Calculating the classes Y_class
#
#
Y_class = np.zeros(Y_prob.shape)
Y_class[np.argmax(Y_prob, axis = 0),np.arange(m)]=1

print("Z=",z)
print("Y_prob=",Y_prob)
print("Y_class=",Y_class)


Z= [[-3.23134684 -0.69025769 -5.0057793  -3.71701779 -1.80186273]
 [ 0.64356189  0.72891688  2.33954505  2.41227437 -0.12318231]
 [-1.6240481  -3.13297332 -3.60870694 -2.12828322  0.22836912]]
Y_prob= [[1.84612148e-02 1.91547711e-01 6.43508665e-04 2.15049777e-03
  7.15597700e-02]
 [8.89429959e-01 7.91802104e-01 9.96754564e-01 9.87317337e-01
  3.83451621e-01]
 [9.21088257e-02 1.66501845e-02 2.60192765e-03 1.05321650e-02
  5.44988609e-01]]
Y_class= [[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 1.]]


Extrapoints: If the label data is Y = [2, 0, 1, 2, 0]. Calculate dW and dB.


In [ ]:
Y = np.array([[0,0,1],[1,0,0],[0,1,0],[0,0,1],[1,0,0]]).transpose()

dW = -np.dot((Y-Y_prob),X.T)/m

In [ ]:
dW

array([[-0.22307886, -0.1214153 ,  0.05845516, -0.03170216,  0.14037119,
        -0.25833221],
       [ 0.14798788, -0.21500614, -0.27986172,  0.06215345,  0.2992932 ,
        -0.5124235 ],
       [ 0.07509098,  0.33642143,  0.22140656, -0.03045129, -0.43966439,
         0.77075572]])

In [ ]:
dW

array([[ 1.11539429,  0.60707649, -0.29227581,  0.15851081, -0.70185597,
         1.29166107],
       [-0.73993939,  1.07503068,  1.39930859, -0.31076726, -1.49646598,
         2.56211752],
       [-0.37545491, -1.68210717, -1.10703278,  0.15225645,  2.19832195,
        -3.85377859]])